# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly
matrix:
    allow_failures:
        - julia: nightly
        - julia: 0.4
        - julia: 0.5
notifications:
    email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Indicators")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Indicators")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
