# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly
matrix:
    allow_failures:
        - julia: nightly
        - julia: 0.4
notifications:
    email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Indicators"); Pkg.test("Indicators"; coverage=true)'
